# Generated by Django 3.2.6 on 2021-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_studentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
