# Generated by Django 3.2.6 on 2021-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211001_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulity',
            field=models.CharField(choices=[('Trung bình', 'Trung bình'), ('Khó', 'Khó'), ('Dễ', 'Dễ')], max_length=10),
        ),
    ]
