# Generated by Django 3.2.6 on 2021-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20211003_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulity',
            field=models.CharField(choices=[('Khó', 'Khó'), ('Dễ', 'Dễ'), ('Trung bình', 'Trung bình')], max_length=10),
        ),
    ]
