# Generated by Django 3.2.6 on 2021-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[('Nữ', 'Nữ'), ('Nam', 'Nam'), ('Khác', 'Khác')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.IntegerField(choices=[('Nữ', 'Nữ'), ('Nam', 'Nam'), ('Khác', 'Khác')]),
        ),
    ]
