# Generated by Django 3.2.6 on 2021-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211001_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
