# Generated by Django 3.2.6 on 2021-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[('Nữ', 'Nữ'), ('Nam', 'Nam'), ('Khác', 'Khác')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.IntegerField(choices=[('Nữ', 'Nữ'), ('Nam', 'Nam'), ('Khác', 'Khác')], max_length=20),
        ),
    ]
